### ISSUE TITLE
Extension doesn't work anymore

### ISSUE THREAD

**Issue by phauer** [daattali/gslides-betternotes-extension#13]
Hi Dean, 
first of all, I like to thank you for this great extension. I use it frequently and it really improves the quality of my talks. 

Unfortunately, since 2 - 4 days, the extension doesn't work anymore (last Wednesday was the last time I used it). When I now enter the presentation mode, there is no slider for resizing the size of the preview anymore. I guess there was an update in Google Slides. 

I'm using Chrome 69 and Ubunutu 16.04 & 17.08. 

I'm not sure if you are still maintaining this great extension, but I keep my fingers crossed. :-) 

Kind Regards, 
Philipp

**Comment by daattali** [comment]
Hi Philipp,

This happened once in the past, and it was indeed because of an update in
Slides. I'm guessing either a Chrome or Slides update is causing this break
too.

I don't have any bandwidth to look at it right now between my other
projects, but thanks for reporting this, I'll try to look when possible.


---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by daattali** [comment]
I've gotten 6 other reports about this. So apparently more people than I realized use this extension :) *

If someone wants to try to tackle this, I'd be happy to pay $15 if you find the issue and submit a fix just because I don't know when I'll get around to it and I don't want the users to suffer for too long

\* according to my developer dashboard, almost 50k weekly users... didn't know this!

**Comment by daattali** [comment]
Fixed (will be on the chrome store in a couple hours)
