### ISSUE TITLE
Audience tools update broke the extension

### ISSUE THREAD

**Issue by PascalTemel** [daattali/gslides-betternotes-extension#5]
Google pushed an update on May 4th to add audience tools to the presenter view, and now the extension doesn't work.

**Comment by daattali** [comment]
Thanks for letting me know.

I just took a look, and I actually think there's a bug on Google's end , and I think they'll catch it eventually and fix it.  I don't think I should fix it on my end.  

In order to  identify if a window is the "speaker notes" window, what I do is I look if the body tag has an attribute called "aria-label" with the value of "speaker notes".  It looks like Google messed up the HTML a bit with the new update because this is what the HTML currently looks like:

```
<body aria-label=""Speaker" notes">
```

It looks like they accidentally put quotation marks around the word "speaker" and it shouldn't be there.  Hopefully they'll notice it and fix it soon.

**Comment by ehoutsma** [comment]
Why do you look at the aria-label? Isn't it better to look at the location of the window? 

The pathname of the window.top.location ends with /present if you are in the presenter view. That way every language can use your tool, and you aren't elimination these kind of errors.

Instead of:
`if (i18n.indexOf(encodeURI(window.top.document.body.getAttribute("aria-label").toLowerCase())) == -1) {`
This would be better:

```
      if (!window.top.location.pathname.endsWith('/present')) {
        return;
      }
```

**Comment by PascalTemel** [comment]
Thanks for the quick reply. This issue has unfortunately ruined my plans for two presentations that I had to hold today. I know it's not your fault, google should really have this resize feature without the need of an extension.

**Comment by ehoutsma** [comment]
I've created a pull-request which solves this problem and should prevent this problem to show in the future.

**Comment by daattali** [comment]
Thanks for your input, I'll take a look when I get home. Sorry for you
troubles

---

http://deanattali.com

**Comment by daattali** [comment]
thanks both

Fixed
